
#CRUD DOCENTES
#CARGAR COMBOBOX DIRECCION, MUNICIPIO(SEGUN DPTO), ALDEA(SEGUN MUNI)
#CARGAR COMBOBOX COLEGIO, TIPO DE ACUERDO,CARGO, DGV DOCENTES, CENTRO EDUCATIVO, 

#CENTROS EDUCATIVOS
#CARGAR LOS COMBOBOX DE DIRECCIONES, DGV CENTROS EDUCATIVOS

#COLEGIO
#CARGAR DGV COLEGIO------------HECHO

#AREA GEOGRAFICA
#CARGAR COMBOBOX DE DIRECCIONES

#DOCENTES EN CE
#CARGAR EL DGV DOCENTES EN CE

#PARTE MENSUAL
#PENDIENTE....

#Call cargar_Cmb_Muni (14)
Call Cargar_Cmb_Aldea (7)


